#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long N, long long X, std::vector<long long> A) {
  for (long long i = 0; i < N; i++) {
    if (X == A[i]) {
      std::cout << YES << std::endl;
      return;
    }
  }
  std::cout << NO << std::endl;
}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long N;
  std::scanf("%lld", &N);
  long long X;
  std::scanf("%lld", &X);
  std::vector<long long> A(N);
  for (int i = 0; i < N; i++) {
    std::scanf("%lld", &A[i]);
  }
  solve(N, X, std::move(A));
  return 0;
}
