#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

void solve(long long N) {
  std::bitset<10> bits;
  for (int i = 0; i < 10; i++) {
    if ((N / (1 << i) % 2) == 1) {
      bits[i] = 1;
    } else {
      bits[i] = 0;
    }
  }
  for (int i = 0; i < 10; i++) {
    std::cout << bits[10 - i - 1];
  }
  std::cout << std::endl;
}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long N;
  std::scanf("%lld", &N);
  solve(N);
  return 0;
}
