#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long H, long long W, std::vector<std::vector<long long>> X, long long Q, std::vector<long long> A, std::vector<long long> B, std::vector<long long> C, std::vector<long long> D){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long H;
    std::scanf("%lld", &H);
    long long W;
    std::scanf("%lld", &W);
    std::vector<std::vector<long long>> X(H, std::vector<long long>(W));
    for(int i = 0 ; i < H ; i++){
        for(int j = 0 ; j < W ; j++){
            std::scanf("%lld", &X[i][j]);
        }
    }
    long long Q;
    std::scanf("%lld", &Q);
    std::vector<long long> A(Q);
    std::vector<long long> B(Q);
    std::vector<long long> C(Q);
    std::vector<long long> D(Q);
    for(int i = 0 ; i < Q ; i++){
        std::scanf("%lld", &A[i]);
        std::scanf("%lld", &B[i]);
        std::scanf("%lld", &C[i]);
        std::scanf("%lld", &D[i]);
    }
    solve(H, W, std::move(X), Q, std::move(A), std::move(B), std::move(C), std::move(D));
    return 0;
}
