#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

void solve(long long N, long long K) {
  int count = 0;
  for (long long i = 1; i <= N; i++) {
    for (long long j = 1; j <= N; j++) {
      if ((0 < K - i - j) && (K - i - j <= N)) {
        count++;
      }
    }
  }
  std::cout << count << std::endl;
}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long N;
  std::scanf("%lld", &N);
  long long K;
  std::scanf("%lld", &K);
  solve(N, K);
  return 0;
}
