#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long M, long long K, std::vector<long long> A, std::vector<long long> S, std::vector<long long> B, std::vector<long long> T){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long M;
    std::scanf("%lld", &M);
    long long K;
    std::scanf("%lld", &K);
    std::vector<long long> A(M);
    std::vector<long long> S(M);
    std::vector<long long> B(M);
    std::vector<long long> T(M);
    for(int i = 0 ; i < M ; i++){
        std::scanf("%lld", &A[i]);
        std::scanf("%lld", &S[i]);
        std::scanf("%lld", &B[i]);
        std::scanf("%lld", &T[i]);
    }
    solve(N, M, K, std::move(A), std::move(S), std::move(B), std::move(T));
    return 0;
}
