#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long T, std::vector<long long> P, std::vector<long long> Q, std::vector<long long> R){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long T;
    std::scanf("%lld", &T);
    std::vector<long long> P(T);
    std::vector<long long> Q(T);
    std::vector<long long> R(T);
    for(int i = 0 ; i < T ; i++){
        std::scanf("%lld", &P[i]);
        std::scanf("%lld", &Q[i]);
        std::scanf("%lld", &R[i]);
    }
    solve(T, std::move(P), std::move(Q), std::move(R));
    return 0;
}
